spring.application.name=restful-sample-jpa

spring.datasource.username=postgres
spring.datasource.password=pass12345
spring.datasource.url=jdbc:postgresql://postgres-cont:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# here we will configure jpa and database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#22a93386f5d65db3e1c47eee019b1c1c2031c340d97866a3c87953e5025fc2a9